services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - ${PORT}:${PORT}
    restart: always
    depends_on:
      - postgres
    volumes:
      - .:/app
      - node-modules:/app/node_modules
      - ./logs:/app/logs
    networks:
      - home-library
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - home-library
networks:
  home-library:
    driver: bridge
volumes:
  postgres-data:
  node-modules:
